<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hexadrone</name>
  <version>0.0.0</version>
  <description>Hexadrone Gazebo simulation package for KRTI 2025</description>
  <maintainer email="gareth.harrison@binus.ac.id">Gareth Harrison</maintainer>
  <maintainer email="maulana.muammar@binus.ac.id">Maulana Mu'ammar</maintainer>
  <license>MIT</license>
  <author>Gareth Harrison</author>
  <author>Maulana Mu'ammar</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_lint_auto</test_depend>
  <exec_depend>ardupilot_gazebo</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>